import { Request, Response } from 'express';
import { db } from '../db';
import { inquiries } from '../db/schema';
import { eq } from 'drizzle-orm';
import { InquiryItem } from '../types/SiteContent';
import nodemailer from 'nodemailer';

// Helper function to send email notification
async function sendEmailNotification(inquiry: any) {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_PASS;

  if (!user || !pass || user === 'your-email@gmail.com') {
    console.warn("⚠️ Gmail credentials not configured in .env, skipping email notification.");
    return;
  }

  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user, pass }
    });

    const mailOptions = {
      from: `"Studio Portal" <${user}>`,
      to: user, // Send to the studio owner's email
      replyTo: inquiry.email,
      subject: `New Inquiry: ${inquiry.name} - ${inquiry.service}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
          <h2 style="color: #C19B6C; border-bottom: 1px solid #eee; padding-bottom: 10px;">New Studio Inquiry</h2>
          
          <p><strong>Name:</strong> ${inquiry.name}</p>
          <p><strong>Email:</strong> <a href="mailto:${inquiry.email}">${inquiry.email}</a></p>
          <p><strong>Phone:</strong> ${inquiry.phone || 'N/A'}</p>
          <p><strong>Coverage Type:</strong> ${inquiry.service}</p>
          <p><strong>Event Date:</strong> ${inquiry.weddingDate || 'N/A'}</p>
          <p><strong>Venue Location:</strong> ${inquiry.venue || 'N/A'}</p>
          <p><strong>Budget:</strong> ${inquiry.budget || 'N/A'}</p>
          
          <div style="margin-top: 20px; padding: 15px; background: #f9f9f9; border-left: 4px solid #C19B6C;">
            <strong>Message from Client:</strong><br><br>
            ${inquiry.message.replace(/\n/g, '<br>') || 'No message provided.'}
          </div>
          
          <p style="margin-top: 30px; font-size: 12px; color: #999;">
            This email was automatically generated by your Studio CMS.
          </p>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("✅ Email notification sent:", info.messageId);
  } catch (error) {
    console.error("❌ Failed to send email notification:", error);
  }
}

export class InquiryController {
  static async addInquiry(req: Request, res: Response) {
    try {
      const inqData = req.body;
      
      const newInquiry = {
        id: `inq-${Date.now()}`,
        name: inqData.name || "Client",
        partnerName: inqData.partnerName || "",
        email: inqData.email || "",
        phone: inqData.phone || "",
        service: inqData.service || "General Inquiry",
        weddingDate: inqData.weddingDate || "",
        venue: inqData.venue || "",
        budget: inqData.budget || "$4,000 - $6,000",
        message: inqData.message || "",
        howFound: inqData.howFound || "",
        status: "new",
      };

      await db.insert(inquiries).values(newInquiry);
      
      // Fire-and-forget the email notification
      sendEmailNotification(newInquiry).catch(e => console.error("Email error:", e));

      res.json({ success: true, inquiry: newInquiry });
    } catch (error) {
      console.error(error);
      res.status(500).json({ success: false, error: 'Failed to add inquiry to database' });
    }
  }

  static async updateInquiryStatus(req: Request, res: Response) {
    try {
      const { id, status } = req.body;
      
      await db.update(inquiries)
        .set({ status })
        .where(eq(inquiries.id, id));
      
      res.json({ success: true });
    } catch (error) {
      console.error(error);
      res.status(500).json({ success: false, error: 'Failed to update inquiry status' });
    }
  }

  static async deleteInquiry(req: Request, res: Response) {
    try {
      const { id } = req.query;
      if (!id || typeof id !== 'string') {
        return res.status(400).json({ success: false, error: 'Missing inquiry ID' });
      }

      await db.delete(inquiries).where(eq(inquiries.id, id));
      res.json({ success: true });
    } catch (error) {
      console.error(error);
      res.status(500).json({ success: false, error: 'Failed to delete inquiry' });
    }
  }
}
